### ISSUE TITLE
Error when launching pulsar-express

### ISSUE THREAD

**Issue by bbonnin** [bbonnin/pulsar-express#4]
After installing using the command: `npm install pulsar-express -g`

we get the following error:
```
$ pulsar-express.js 

        ╭────────────────╮
        │ PULSAR EXPRESS │
        ╰────────────────╯

/usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1
var __global__ = this;(function (require, module, __shared__) { var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,function(){return e}},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SAFE_INTEGER

TypeError: e.charCodeAt is not a function
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:278667
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:161905
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:162158
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:278634
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:278940
    at Object.<anonymous> (/usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:290304)
    at r (/usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:601)
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:793
    at /usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:803
    at D (/usr/local/lib/node_modules/pulsar-express/node_modules/esm/esm.js:1:760)
```

**Comment by bbonnin** [comment]
Fix in v0.1.2
